### ISSUE TITLE
Plugin doesn't work. 

### ISSUE THREAD

**Issue by aVitaliy** [chr233/CardTradeExtension#13]
Plugin doesn't work.
I used plugin version 1.0.8.2 and 2.0.0.0
ASF version 5.4.12.5 - win-x64

I send the command in chat:
!2SENDCARDSET Bot1 730 5 https://steamcommunity.com/tradeoffer/new/?partner=ХХХХХХХ&token=ХХХХХХХ

I don't understand what the problem is? How to solve this problem?
Gives an error message.

**Comment by aVitaliy** [comment]
ASFenhance encountered error, error logs below
==========================================================================
 - Origin Message: 2SENDCARDSET Bot1 730 5 https://steamcommunity.com/tradeoffer/new/?partner=XXXXXXXX&token=XXXXXX
 - Access: Owner
 - ASF Version: 5.4.12.5
 - Plugin Version: 2.0.0.0
==========================================================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false,
  "DisabledCmds": null,
  "Address": null,
  "Addresses": []
}
==========================================================================
 - Exception Type: System.MissingMethodException
 - Exception Message: Attempted to access a missing method.
   at ASFTradeExtension.Card.Handler.GetAppCardBundle(Bot bot, UInt32 appId, IEnumerable`1 inventory)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFTradeExtension.Card.Handler.GetAppCardBundle(Bot bot, UInt32 appId, IEnumerable`1 inventory)
   at ASFTradeExtension.Card.Command.ResponseSendCardSet(Bot bot, String strAppId, String strSetCount, String tradeLink, Boolean autoConfirm)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFTradeExtension.Card.Command.ResponseSendCardSet(String botNames, String strAppId, String strSetCount, String tradeLink, Boolean autoConfirm)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)

**Comment by chr233** [comment]
lol, new version will be released in 5 days

**Comment by chr233** [comment]
some functions required Linq, use ASF-generic version may fix the problem

new version will avoid this problem

**Comment by aVitaliy** [comment]
I've never used the ASF-generic version.
Installed SDK 7.0.403 and ArchiSteamFarm V5.4.12.5 and ASF-generic.zip on Windows 11
After this, ASF was able to send 5 sets of cards and the bot received these 5 sets of cards. Thank you for telling me how to fix this.
P.S. Although I think that a regular plugin for ASF-win-x64 is preferable.

**Comment by chr233** [comment]
I see, but I'm working on another plugin recently, I will fix this plugin after that. Something that can be guaranteed is there will be a inventory cache in new version of this plugin.
