### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Semidvista** [chr233/CardTradeExtension#14]
>
2SENDCARDSET 0.HustleHardy xxxxxxx 3 [https://steamcommunity.com/tradeoffer/new/?partner=xxxxxx&token=xxxxxxxx](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fsteamcommunity.com%2Ftradeoffer%2Fnew%2F%3Fpartner%3Dxxxxxx%26token%3Dxxxxxxxx)
<
ASFTradeExtension обнаружил ошибку, журнал ошибок ниже
==========================================
- Origin Message: 2SENDCARDSET 0.HustleHardy xxxxxx 3 [https://steamcommunity.com/tradeoffer/new/?partner=xxxx&token=xxxxxx](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fsteamcommunity.com%2Ftradeoffer%2Fnew%2F%3Fpartner%3Dxxxx%26token%3Dxxxxxx)
- Доступ: Owner
- Версия ASF: 5.5.0.11
- Версия плагина: 1.0.8.0
==========================================
{
"EULA": true,
"Statistic": true,
"DisabledCmds": [],
"MaxItemPerTrade": 255
}
==========================================
- Exception Type: System.MissingMethodException
- Сообщение об ошибке: Attempted to access a missing method.
at ASFTradeExtension.Card.Handler.GetAppCardBundle(Bot bot, UInt32 appId, IEnumerable`1 inventory)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
at ASFTradeExtension.Card.Handler.GetAppCardBundle(Bot bot, UInt32 appId, IEnumerable`1 inventory)
at ASFTradeExtension.Card.Command.ResponseSendCardSet(Bot bot, String strAppId, String strSetCount, String tradeLink, Boolean autoConfirm)
at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
at ASFTradeExtension.Card.Command.ResponseSendCardSet(String botNames, String strAppId, String strSetCount, String tradeLink, Boolean autoConfirm)
at ASFTradeExtension.ASFTradeExtension.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
![Uploading h1cy3N-rJoI.jpg…]()

**Comment by chr233** [comment]
still WIP
