### ISSUE TITLE
Plugin does not work at all

### ISSUE THREAD

**Issue by SENPAY98K** [chr233/CardTradeExtension#16]
**Describe the bug / Bug 描述**
I just installed the plugin and tried `FULLSETLIST` and `FULLSET`, after that i get this error in console

**Error Log / 错误日志**
![image](https://github.com/user-attachments/assets/b84d52e4-0d1f-42f6-a704-2ee0e506affa)

```txt
ASFTradeExtension 遇到错误, 日志如下
==========================================
 - 原始消息: TEST
 - Access: Owner
 - ASF 版本: 6.0.4.4
 - 插件版本: 1.1.2.0
==========================================
ReloadBotCache() System.MissingMethodException: Attempted to access a missing method.
   at ASFTradeExtension.Core.InventoryHandler.GetAppCardGroupLazyLoad(List`1 inventory)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFTradeExtension.Core.InventoryHandler.GetAppCardGroupLazyLoad(List`1 inventory)
   at ASFTradeExtension.Core.InventoryHandler.ReloadBotCache()
```

**Comment by chr233** [comment]
use ASF-Generic
