### ISSUE TITLE
这错误咋搞

### ISSUE THREAD

**Issue by fancyword** [chr233/CardTradeExtension#4]
ASFTradeExtension 遇到错误, 日志如下
==========================================
 - 原始消息: fsl 小号01
 - Access: Owner
 - ASF 版本: 5.4.8.3
 - 插件版本: 1.0.6.1
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DisabledCmds": [],
  "MaxItemPerTrade": 255
}
==========================================
 - 错误类型: System.MissingMethodException
 - 错误消息: Attempted to access a missing method.
   at ASFTradeExtension.Card.Handler.GetAppCardGroup(Bot bot, IEnumerable`1 appIds, IEnumerable`1 inventory)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFTradeExtension.Card.Handler.GetAppCardGroup(Bot bot, IEnumerable`1 appIds, IEnumerable`1 inventory)
   at ASFTradeExtension.Card.Command.ResponseFullSetList(Bot bot, String query)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFTradeExtension.Card.Command.ResponseFullSetList(String botNames, String query)
   at ASFTradeExtension.ASFTradeExtension.ResponseCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
   at ASFTradeExtension.ASFTradeExtension.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)

**Comment by chr233** [comment]
换用 generic 后缀的ASF
